fugue/regula

rules/admin_policy.rego, rules/user_attached_policy.rego, tests/rules/inputs/user_attached_policy.rego, tests/rules/inputs/user_attached_policy.tf, tests/rules/user_attached_policy.rego
For REGULA_R00001: IAM policies should not be attached to users. This maps to CIS 1.16.
- Updated REGULA_R00002 with rule number in comments
- Added Rego rule user_attached_policy.rego
- Added corresonding Terraform file
- Added corresponding Rego test file
- Added corresponding Rego test input file
All tests passed.
=> REGULA_R00001 

rules/no_ingress_except_80_443.rego, tests/rules/inputs/no_ingress_except_80_443.rego, tests/rules/inputs/no_ingress_except_80_443.tf, tests/rules/no_ingress_except_80_443.rego
For REGULA_R00008: VPC security group rules should not permit ingress from '0.0.0.0/0' except to ports 80 and 443
- Added Rego rule no_ingress_except_80_443.rego
- Added corresonding Terraform file
- Added corresponding Rego test file
- Added corresponding Rego test input file
All tests passed.
=> REGULA_R00008

bin/regula
The latter doesn't work on Mac.
=> Use `mktemp -t `rather than `mktemp --tmpdir`

README.md
This PR fixes the sample Regula output so it's more general instead of from the GitHub Action. It also fixes some links that pointed to the wrong files, and adds the full path to the link text.
=> Small README tweaks; fix links, clarify output

README.md
This PR updates the README to add prerequisites (downloading/installing OPA, Terraform 0.12+) and Windows commands.
=> Update README -- add prerequisites, Windows instructions

README.md, conftest/regula.rego, lib/fugue_regula_conftest.rego
Add a small conftest integration library and document how to use conftest together with Regula.
Note that the instructions in the README currently do not work since these changes are not on `master` yet, so the following pull URLs need to be used instead:
conftest pull -p policy/regula/lib 'git@github.com:fugue/regula.git//lib?ref=conftest'
conftest pull -p policy/regula/rules 'git@github.com:fugue/regula.git//rules?ref=conftest'
=> Conftest integration

conftest/regula.rego, examples/aws/tag_all_resources.rego, lib/fugue.rego, lib/fugue_regula.rego, tests/examples/aws/inputs/tag_all_resources_infra.rego, tests/examples/aws/inputs/tag_all_resources_infra.tf, tests/examples/aws/tag_all_resources_test.rego
This adds support for `fugue.deny_resource_with_message` and
`fugue.missing_resource_with_message`, which will soon be supported
in Fugue.
The custom error messages are included in the JSON output,
human-readable output and conftest output.
=> Custom error messages support

tests/lib/fugue_regula_report_test.rego, tests/lib/fugue_regula_test.rego
Adds a test that uses `with data.rules ...` to mock the rules as well
as the input.  This gives us much better coverage.  Requires
<https://github.com/fugue/fregot/issues/178> for running this with
`fregot`.
=> Better report testing

conftest/regula.rego
This PR enables structured output for conftest and includes the rule_name and resource in the JSON output. This is really valuable to us, as we're looking to do some post-processing on the output.
conftest's stdout, tap, table, and junit output remains unchanged. conftest's json output, however, now looks like this:
```json
[
{
"filename": "policy/test_inputs/new_tagging_standard_infra-plan.json",
"warnings": [],
"failures": [
{
"msg": "regula: Rule new_tagging_standard failed for resource aws_instance.fail_no_tags: Resource is taggable but has no tags (or ASG tags not set to propagate at launch)\n",
"metadata": {
"resource": "aws_instance.fail_no_tags",
"rule_name": "new_tagging_standard"
}
}
],
"successes": []
}
]
```
=> enable structured output for conftest

lib/fugue_regula.rego, rules/aws/cloudfront_distribution_https.rego, rules/aws/cloudtrail_log_file_validation.rego, rules/aws/ebs_volume_encrypted.rego, rules/aws/iam_admin_policy.rego, rules/aws/iam_user_attached_policy.rego, rules/aws/kms_rotate.rego, rules/aws/s3_bucket_sse.rego, rules/aws/security_group_ingress_anywhere.rego, rules/aws/security_group_ingress_anywhere_rdp.rego, rules/aws/security_group_ingress_anywhere_ssh.rego, rules/aws/vpc_flow_log.rego, rules/azure/network_security_group_no_inbound_22.rego, rules/azure/network_security_group_no_inbound_3389.rego, rules/azure/network_security_rule_no_inbound_22.rego, rules/azure/network_security_rule_no_inbound_3389.rego, rules/azure/sql_server_firewall_no_inbound_all.rego, rules/azure/storage_account_deny_access.rego, rules/azure/storage_account_microsoft_services.rego, rules/azure/storage_account_secure_transfer.rego, rules/azure/storage_container_private_access.rego, rules/gcp/compute_firewall_no_ingress_22.rego, rules/gcp/compute_firewall_no_ingress_3389.rego, rules/gcp/compute_subnet_flow_log_enabled.rego, rules/gcp/compute_subnet_private_google_access.rego, rules/gcp/kms_cryptokey_rotate.rego, tests/lib/fugue_regula_report_test.rego
This PR implements the proposed [regodoc standard](https://hackmd.io/@ZtQnh19kS26YiNlJLqKJnw/H1gAv5nBw) for rule metadata. I've also added and changed some information for each rule.
Adopting this standard allows us to embed rule metadata in a format that is easy to process with other tools.
* ID
* The IDs are sourced from Fugue's rule database
* Title
* Description
* Severity
* Compliance family
* This was previously implied by the prefix of the control tag, but is now used as a way to group controls
* Removed the `REGULA_...` entries in controls
* Standardized control tags to Fugue's rule database
* Control tags refer to the control names / IDs, e.g. `CIS_1-1`
Apart from the changed information mentioned above, each `rules` entry in the report output will contain a `metadata` entry: …
=> Use rego metadoc for rule metadata

README.md
ec2 prefix is missing the test rule and  package name in README.md
https://github.com/fugue/regula/blob/master/tests/examples/aws/ec2_t2_only_test.rego#L14
=> typo fix for ec2_t2_only rule and package name

README.md, bin/regula
add parameter --terraform-dir,  --terraform-json and --rego-paths to be able to consume existing json plan file instead of creating from scratch
=> add option to use existing json

rules/aws/security_group_ingress_anywhere.rego, rules/azure/network_security_group_no_inbound_22.rego, rules/azure/network_security_group_no_inbound_3389.rego, rules/gcp/compute_firewall_no_ingress_22.rego, rules/gcp/compute_firewall_no_ingress_3389.rego, rules/gcp/compute_subnet_flow_log_enabled.rego, rules/gcp/kms_cryptokey_rotate.rego
I assigned new rule IDs to a several rules because of conflicts with existing rules. I also fixed a mistake (that I made) where the IDs of these two rules were swapped:
rules/azure/network_security_group_no_inbound_3389.rego
rules/azure/network_security_group_no_inbound_22.rego
=> Assigned new rule IDs to rules; swapped two other IDs

rules/cfn/s3/cloudtrail_s3_data_logging_read.rego, rules/cfn/s3/cloudtrail_s3_data_logging_write.rego, tests/rules/cfn/s3/cloudtrail_s3_data_logging_read_test.rego, tests/rules/cfn/s3/cloudtrail_s3_data_logging_write_test.rego
This change updates `rules/cfn/s3/cloudtrail_s3_data_logging_read.rego` and `rules/cfn/s3/cloudtrail_s3_data_logging_write.rego` to not evaluate when the template does not contain any trails. We cannot provide a definitive result when these resources are not evaluated together, like when they're defined in different templates.
=> [RM-5219] Skip cloudtrail_s3_data_logging rules in templates without trails

Dockerfile
This PR adds git to the regula Dockerfile. git is used by Terraform to download modules during `terraform init`.
=> Add git to Dockerfile for terraform module support

bin/regula, lib/fugue.rego, lib/fugue/regula.rego, lib/fugue/resource_view/cloudformation.rego, lib/fugue/resource_view/terraform.rego, tests/examples/aws/ec2_t2_only_test.rego, tests/examples/aws/iam_password_length_test.rego, tests/examples/aws/tag_all_resources_test.rego, tests/examples/aws/useast1_only_test.rego, tests/lib/fugue_regula_report_test.rego, tests/lib/fugue_regula_test.rego, tests/lib/fugue_resource_view_01_test.rego, tests/lib/fugue_resource_view_02_test.rego, tests/lib/fugue_resource_view_03_test.rego, tests/lib/fugue_resource_view_cloudformation_test.rego, tests/lib/fugue_resource_view_modules_test.rego, tests/lib/fugue_resource_view_test.rego
This is a work-in-progress PR with updates to the report output format. This will be a breaking change for users and should be be shipped separately from the CloudFormation work. Example output of `./bin/regula` so far:
```json
{
"rule_results": [
{
"controls": [
"CIS-AWS_v1.3.0_1.20"
],
"platform": "cloudformation",
"provider": "aws",
"resource_id": "Bucket",
"resource_type": "AWS::S3::Bucket",
"rule_description": "S3 buckets should have all `block public access` options enabled. AWS's S3 Block Public Access feature has four settings: BlockPublicAcls, IgnorePublicAcls, BlockPublicPolicy, and RestrictPublicBuckets. All four settings should be enabled to help prevent the risk of a data breach.",
"rule_id": "FG_R00229",
"rule_message": "",
"rule_name": "cfn_s3_block_public_access", …
```
=> [RM-5293] Update report output format

bin/regula
This PR fixes a compatibility issue with bash 3.2 where the quotes around our index variable caused this arithmetic expansion to fail.
=> Remove quotes in math expression in regula script

Dockerfile, README.md
Since the input file is no longer specified first, this allows us to add
arguments without having to overwrite the entrypoint.  This does mean that
"simple" usage now requires the `-` parameter:
docker run -i regula:latest - <some_file.cfn
I think this is outweighed by the advantages: this makes it easier to pass in
other arguments, without having to re-specify `/opt/regula/`.  For example:
docker run --rm \
--volume [HCL_DIRECTORY]:/workspace \
fugue/regula \
/workspace
Where we needed the following monstrosity before:
docker run --rm \
--entrypoint regula \
--volume [HCL_DIRECTORY]:/workspace \
fugue/regula \
/workspace \
/opt/regula
=> Update docker to use new entrypoint style

bin/regula
This makes sure the `filename` always shows up in reports (and allows you to
waive on it).
=> [RM-5292] Always use multifile mode

README.md
This is a small docs change to add clarity to the configuration examples in the readme.
=> Add package declaration to config examples

lib/fugue.rego
We currently have the following functions available to advanced rules:
fugue.allow_resource(resource)
fugue.deny_resource(resource)
fugue.deny_resource_with_message(resource, message)
fugue.missing_resource(resource_type)
fugue.missing_resource_with_message(resource_type, message)
We would like to point out _where_ resources are invalid.  This is expressed as
a Rego path to an attribute (e.g. `["port"]` or `["ingress", 0]`).
However, Rego doesn't allow function overloading, and we don't want to keep
adding new versions of this functions using different `_with_xxx` combinations.
This patch adds three new functions:
fugue.allow({"resource": resource})
fugue.deny({"resource": resource})
fugue.missing({"resource_type": resource_type})
These builtins all take more parameters (`message`, …
=> [RM-5341] Add parameter based versions for fugue.{allow,deny}

lib/fugue/resource_view/terraform.rego
For some complex terraform plans involving modules, we were seeing the following
error:
object keys must be unique
This was an error in `configuration_modules`, which walks a large tree and
identifies possible modules.  We were identifying modules by different
properties:
1.  Is an object
2.  The shape of the path
3.  Has a `.resources` attribute
However, check (2) was broken.  This lead to us misidentifying a common resource
as a module (since it also had a `.resources` field); in turn causing two
results (the common resource and the actual module) for the same module path,
leading to the inconsistency error.
Why was check (2) broken?  It had been broken since it was merged, but because
OPA wasn't enforcing the consistency check until recently, we didn't notice.
We were using `all` for …
=> [RM-5590] Fix module detection in terraform resource view

examples/aws/tag_all_resources.rego
This PR fixes an issue where multiple tags under 6 characters results in a `functions must not produce multiple outputs for same inputs` error in this example rule.
=> Fix bug in tag_all_resources example rule

README.md
This PR shortens the README to guide users to the newly launched [regula.dev](https://regula.dev) docs site.
It retains installation, usage, and some other content but adds links to the appropriate documentation.
=> Shorten README and officially launch Regula docs site

pkg/loader/tf.go, pkg/loader/tf_test/example-terraform-modules.json, pkg/loader/tf_test/file.json, pkg/loader/tf_test/resource-local-ref.json, pkg/rego/load.go
This PR includes two small bug fixes:
* Exclude the `hashicorp/` prefix in the provider field in the TF loader. This change makes the behavior match what you'd get from evaluating an equivalent Terraform plan.
* Ignore non-rego files when loading an individual rego file. I was already checking against the `opaExts` set when a directory gets passed to `regula test`, `regula repl`, `regula run --include`, etc. But, I forgot to do the same when an individual file is specified.
=> Small bug fixes

pkg/reporter/base.go, pkg/reporter/junit.go
CircleCI doesn't show the test suite names from JUnit XML. This PR adds the file path to the JUnit test case name in the JUnit output format. An example of what this will look like in CircleCI is:
```
src/cloudformation.yaml#SomeResource
```
```
src/cloudformation.yaml#SomeResource - AWS::Service::ResourceType
```
This behavior is similar to some scripts we've used in the past.
=> Include filepath in JUnit test case names

changes/unreleased/Fixed-20210602-141014.yaml, pkg/reporter/table.go
This PR changes the table output so that `WAIVED` status and severity use the default foreground color. We were using black, which is difficult to read in dark color schemes.
=> [RM-5634] #126 Remove coloring for WAIVED status and severity

pkg/loader/tf.go, pkg/loader/tf_test/count-local.json, pkg/loader/tf_test/count-local/main.tf, pkg/loader/tf_test/count-var.json, pkg/loader/tf_test/count-var/main.tf
This works by turning our interface/JSON-like values back into the native HCL/cty values and passing them in that way.
=> [RM-5431] Improve support for count, locals, variables

rego/rules/cfn/vpc/nacl_ingress_22.rego, rego/rules/cfn/vpc/nacl_ingress_3389.rego
This PR fixes a small issue I noticed while reviewing rules - `input_type` and `resource_type` are missing for these two.
=> Add input and resource type to cfn nacl rules

cmd/normalize_flag.go, cmd/repl.go, cmd/run.go, cmd/show.go, cmd/test.go, cmd/write_test_inputs.go, go.mod, go.sum, pkg/loader/base.go
This is a small PR to allow users to use `_` as the word-separator in the Regula CLI flags and flag values, for example `--input_type tf_plan` works the same as `--input-type tf-plan`. The `normalizeFlag` function normalizes `--input_type` -> `--input-type`. For our enum flag values (like the `--input-type` values) we'll need to add aliases to the name map for the type, like in the `pkg/loader/base.go` change.
=> [RM-5656] Accept _ in flag names, e.g. "--input_type=tf_plan"

rego/rules/tf/aws/cloudtrail/log_file_validation.rego, rego/rules/tf/aws/ebs/volume_encrypted.rego, rego/rules/tf/aws/iam/admin_policy.rego, rego/rules/tf/aws/iam/user_attached_policy.rego, rego/rules/tf/aws/kms/key_rotation.rego, rego/rules/tf/aws/s3/bucket_sse.rego, rego/rules/tf/aws/security_group/ingress_anywhere_rdp.rego, rego/rules/tf/aws/security_group/ingress_anywhere_ssh.rego, rego/rules/tf/aws/vpc/flow_log.rego, rego/rules/tf/azurerm/storage/account_deny_access.rego, rego/rules/tf/azurerm/storage/account_microsoft_services.rego, rego/rules/tf/azurerm/storage/container_private_access.rego, rego/rules/tf/google/compute/firewall_no_ingress_22.rego, rego/rules/tf/google/compute/firewall_no_ingress_3389.rego, rego/rules/tf/google/compute/subnet_flow_log_enabled.rego, rego/rules/tf/google/compute/subnet_private_google_access.rego, rego/rules/tf/google/kms/cryptokey_rotate.rego, rego/tests/rules/tf/google/kms/inputs/cryptokey_rotate_infra.json, rego/tests/rules/tf/google/kms/inputs/cryptokey_rotate_infra.tf, rego/tests/rules/tf/google/kms/inputs/cryptokey_rotate_infra_json.rego
This PR makes a few changes to rule compliance mappings and metadata:
* Adds `severity` where it was missing
* Note that we'll still have one rule without a severity: `rego/rules/tf/aws/security_group/ingress_anywhere.rego`
* Adds `CIS-AWS_v1.3.0` mappings to the terraform AWS rules.
* Updates the IDs and descriptions for a few Google rules where we had duplicates.
* Updates one of the Google rules for CIS-Google_v1.1.0: `rego/rules/tf/google/kms/cryptokey_rotate.rego`
* The latest version of the spec enforces rotation every 90 days instead of every 365 days. I updated the tests to match.
=> [RM-5669] Rule compliance mapping and severity updates

go.mod, pkg/loader/tf.go
This PR fixes a panic when reading HCL from stdin. The way this fix works is that when an input is stdin, we'll use Afero's `MemMapFs` (instead of the default `OsFs` that we get from passing `nil` to `NewParser()`) and make an in-memory file with stdin's contents.
Just reading stdin
```shell
./bin/regula run < ./rego/tests/rules/tf/aws/s3/inputs/bucket_sse_infra.tf  
{
"rule_results": [
{
"controls": [
"CIS-AWS_v1.2.0_2.8",
"CIS-AWS_v1.3.0_3.8"
],
"filepath": "<stdin>",
"platform": "terraform",
"provider": "aws",
"resource_id": "aws_kms_key.key",
"resource_type": "aws_kms_key",
"rule_description": "KMS CMK rotation should be enabled. It is recommended that users enable rotation for the customer created AWS Customer Master Key (CMK). Rotating encryption keys helps reduce the potential …
```
=> [RM-5686] Fix bug when reading HCL from stdin

cmd/run.go, cmd/show.go, cmd/write_test_inputs.go
Change the type names for all the enum flags to `string` so that they're consistent with other args.
=> Change arg type names in help text to string

rego/lib/fugue/input_type.rego
This PR adds an "unknown" result for `fugue.input_type`. This guarantees that `fugue.input_type` will be defined when `input` is empty or undefined.
=> [RM-5678] Add "unknown" result for input_type

pkg/loader/tf.go, rego/lib/fugue/resource_view/terraform.rego, rego/tests/lib/fugue_resource_view_01_test.rego, rego/tests/lib/fugue_resource_view_02_test.rego
This PR changes the way we calculate `_type` for data resources. I was testing with a configuration that has a few [S3 bucket data resources](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/data-sources/s3_bucket) and realized that we don't distinguish between those and managed S3 bucket resources. After this change, data resources will be prefixed with `data.`, like `data.aws_s3_bucket`. This is a potentially breaking change, so it's worth some discussion.
=> Include data. in data resource type names

docs/src/rules.md, mkdocs.yml
This PR adds a Rules List page to the docs site. It temporarily links to the rules directory in the regula repo and will be updated in a forthcoming PR to list all of the rules.
=> Add rules page to docs site

README.md, docs/src/configuration.md, docs/src/development/test-inputs.md, docs/src/development/testing-rules.md, docs/src/development/writing-rules.md, docs/src/development/writing-tests.md, docs/src/examples/waive-and-disable.md, docs/src/examples/writing-a-rule.md, docs/src/getting-started.md, docs/src/integrations/pre-commit.md, docs/src/integrations/travis.md, docs/src/report.md, docs/src/rules.md, docs/src/usage.md, mkdocs.yml
This PR does the following:
- Redirects the Rule Development page to Writing Rules, and splits up the old Rule Development page into 3 pages:
- Writing Tests
- Testing Rules
- Test Inputs
- Adds a pre-commit hook page
- Updates the Travis integration page to link to the new example repo
- Updates output throughout the docs
- Adds `write-test-inputs` documentation
- Adds table of rules to Rules List
=> Update docs for 1.0 release

docs/src/usage.md
This documentation PR explains the `FATAL Unable to detect input type of file` error message when using globbing in commands.
=> Docs: Add note about globbing in commands

rego/rules/tf/azurerm/network/security_group_no_inbound_22.rego, rego/rules/tf/azurerm/network/security_group_no_inbound_3389.rego, rego/rules/tf/azurerm/sql/firewall_no_inbound_all.rego, rego/rules/tf/azurerm/storage/account_deny_access.rego, rego/rules/tf/azurerm/storage/account_microsoft_services.rego, rego/rules/tf/azurerm/storage/account_secure_transfer.rego
These Azure rules were missing CIS-Azure_v1.3.0 mappings. I also fixed an issue with the v1.1.0 mappings where the RDP and SSH ingress controls were backwards.
=> [RM-5772] Add missing CIS-Azure_v1.3.0 mappings

docs/src/development/writing-tests.md
This PR fixes a small error on the [docs site](https://regula.dev/development/writing-tests.html#writing-a-test-for-a-simple-rule).
=> Writing Tests page: Fix package name in Rego example

rego/lib/fugue.rego
This PR fixes a bug where `missing()` rule results don't show up in the report output.
=> Fix missing results excluded from report

pkg/loader/tf.go, pkg/loader/tf_test/vars.json, pkg/loader/tf_test/vars/main.tf
Just returning nil is important here as many terraform modules rely on
this failing to plug in variables using the ternary operator `?:`.
=> [RM-5805] Respect that some variables are not found

Dockerfile, docs/src/getting-started.md, docs/src/usage.md
This PR sets a default `WORKDIR` for the Regula Docker image. It makes the container a little easier to run since you don't have to specify the `--workdir` argument if you mount to `/workspace`. I also added PowerShell to the installation and Docker usage instructions.
=> Set a default WORKDIR in the docker image

pkg/loader/loadpaths.go, pkg/loader/tf.go, pkg/loader/tf_test.go
Go's default filepath.Join reduces `examples/mssql/../../` to `.`.  This
doesn't really align with what we want.  We would want these three paths
to be different:
.
examples/mysql/../../
examples/complete/../../
They represent the main module at `.`, and then two different instantations
of the main module at `.` loaded from different submodules.
By using our own join here we get the desired behaviour.  This helps for
determining the correct source code location in complex repositories.
=> [RM-5761] Smarter path join for tf loader

rego/rules/tf/aws/rds/rds_instance_publicly_accessible.rego
This fixes an issue with `FG_R00278` where we weren't accounting for the default `false` value of `aws_db_instance.publicly_accessible`.
=> [RM-5806] RDS publicly_accessible is false by default

pkg/loader/tf.go
Terraform downloads remote modules that are referenced by other remote modules to the top-level `.terraform` directory rather than to separate `.terraform` directories in each child. This change makes it so we look in that top-level directory instead of in each child directory.
Your top level configuration depends on a remote module `vpc` that depends another remote module `subnets`. Running `terraform init` would download those modules to:
```
.terraform/modules/vpc
.terraform/modules/subnets
```
instead of
```
.terraform/modules/vpc
.terraform/modules/vpc/.terraform/modules/subnets
```
=> Use top-level .terraform directory for nested remote tf modules

pkg/loader/tf.go
This change improves two TF loader warnings:
* The warnings we emit when remote submodules are missing. These currently look like:
```
WARNING Error loading submodule gcp-network: <nil>: Failed to read module directory; Module directory terraform-google-modules/network/google does not exist or cannot be read. 
WARNING Error loading submodule gcs_buckets: <nil>: Failed to read module directory; Module directory terraform-google-modules/cloud-storage/google does not exist or cannot be read.
```
After this PR, we'll collect the missing remote modules into a single warning that mentions `terraform init`:
```
WARNING Could not load some remote submodules. Run 'terraform init' if you would like to include them in the evaluation: terraform-google-modules/network/google, …
```
=> Improving some TF loader warnings

pkg/loader/loadpaths.go
This PR resolves #167. The issue was that a lot of our code produces ['clean' paths](https://pkg.go.dev/path/filepath#Clean) and we weren't accounting for that when we check whether or not we've loaded already loaded a file. This was causing TF files to get loaded twice if the input path had a leading `./`.
=> Normalize file paths in LoadPaths

changes/unreleased/Added-20210812-124517.yaml, cmd/flags.go, cmd/init.go, cmd/repl.go, cmd/run.go, cmd/run.txt, cmd/show.go, cmd/test.go, cmd/write_test_inputs.go, docs/src/configuration.md, docs/src/usage.md, go.mod, go.sum, pkg/loader/auto.go, pkg/loader/base.go, pkg/loader/loadpaths.go, pkg/loader/loadpaths_test.go, pkg/loader/tfplan.go, pkg/rego/builtin.go, pkg/rego/load.go, pkg/rego/rego_test.go, pkg/rego/runrepl.go, pkg/rego/runtest.go
This PR adds a configuration file feature to regula. The configuration file is created through `regula init` command and currently only applies to the `regula run` command.
Because it's only possible to use one configuration file at a time, I've also made it so that `--input-type` can be specified multiple times. I also refactored some of the `cmd` code around flags in order to cut down on repeated descriptions and parsing code.
=> [RM-5612] Regula configuration file

pkg/loader/tf.go, pkg/loader/tf_test/nested-vars-rm5823.json, pkg/loader/tf_test/nested-vars-rm5823/main.tf
The TF loader uses two representations of the document:
1.  The native Go fashion, e.g. `[]interface{}` for arrays,
`map[string]interface{}` for objects, etc.
2.  A more typed version, using the `cty` library.
When dealing with variables, we must sometimes convert from (1) to (2). `cty`
requires lists to be homogenous.  This is usually not a problem since the types
in the schemas enforce this; however, in some cases we don't have these schemas,
and this list ends up looking heterogenous:
[
{
rule_no    = 100
cidr_block = "0.0.0.0/0"
},
{
rule_no         = 101
ipv6_cidr_block = "::/0"
},
]
We work around this by using a tuple instead of a list which allows for
different types.
=> [RM-5823] Fix type mismatch when constructing cty value

rego/lib/fugue/scan_view.rego
We need the input_type here for resources without rule results.
=> [RM-5843] Add input_type to inputs in scan view

pkg/loader/base.go, pkg/loader/input.go, pkg/loader/loadpaths.go, pkg/loader/tf.go
This PR makes two changes:
1. Regula will no longer recurse into directories that have already been loaded. Right now, this situation only occurs for Terraform configurations.
2. It adds the `.terraform` directory to the list of loaded paths for Terraform configurations.
These changes fix a bug where we're loading modules and their examples as separate configurations in some scenarios.
=> [RM-5895] Skip .terraform directory for tf configs

cmd/scan.go, pkg/regotools/doublequote/doublequote.go, pkg/regotools/doublequote/doublequote_test.go, pkg/regotools/metadoc/metadoc.go, pkg/regotools/metadoc/metadoc_test.go
This also moves the metadoc package inside regotools to make the organization a
bit cleaner.
=> [RM-5932] Turn single quotes into double quotes

rego/lib/aws/iam/policy_document_library.rego, rego/lib/aws/s3/s3_library.rego, rego/rules/tf/aws/s3/bucket_config_public_read.rego, rego/rules/tf/aws/s3/bucket_is_public.rego, rego/rules/tf/aws/s3/bucketpolicy_allowall.rego, rego/rules/tf/aws/s3/bucketpolicy_allowlist.rego, rego/rules/tf/aws/s3/https_access.rego, rego/rules/tf/aws/sqs/granular_access.rego
`policy_document_ref_or_json_string` is meant to decide whether or not a policy
document is valid.  However, there was a bug in this function, resulting in all
inputs being treated as valid if a single policy policy data document exists.
However, this is only used in `s3_library.buckets_with_valid_policies`, which is
a bit of an antipattern: it first checked which buckets only have valid (valid
as in well-formatted JSON) policies, and then uses these in whatever rule.
It is much better to just iterate over all buckets and policy pairs, and discard
only the invalid ones.  That way a single invalid policy doesn't cause our
system to skip the other policies.
=> [RM-5934] Remove buckets_with_valid_policies

docs/requirements.txt, mkdocs.yml
This PR adds a Google Analytics code to each page of regula.dev. It also upgrades the Material theme to support this.
Followed the format here: https://squidfunk.github.io/mkdocs-material/setup/setting-up-site-analytics/#google-analytics
=> Add Google Analytics to the docs site

Makefile, pkg/reporter/base.go, pkg/reporter/text.tmpl, rego/embedded.go, rego/remediation.yaml
This is currently a bit hackish; I just added code to check the ID at
the end of the process and inject the link if it's something we have
remediation documentation for.  Longer term it would probably make
sense to move the link into the __rego_metadoc__ blocks in the rego
files, but there is some infrastructure stuff which needs to happen
first.
I decided to leave `rego/rules/remediation.yaml` out of git, which may be the wrong decision... the file is generated (based on rules in the Makefile) using curl, grep, sort, and awk.  This shouldn't be a problem on Linux or macOS, but may be somewhat tricky on Windows.
=> [RM-5916] Add link to rule documentation in output report

pkg/loader/tf.go, pkg/loader/tf_test/template-in-jsonencode.json, pkg/loader/tf_test/template-in-jsonencode/main.tf
This PR adds support for a common usage of jsonencode:
```hcl
resource "aws_s3_bucket" "test1" {
bucket  = "test1"
}
resource "aws_s3_bucket_policy" "test1" {
bucket = "${aws_s3_bucket.test1.id}"
policy = jsonencode({
Version = "2012-10-17"
Id      = "MYBUCKETPOLICY"
Statement = [
{
Sid       = "IPAllow"
Effect    = "Allow"
Principal = "*"
Action    = "s3:List*"
Resource =        "${aws_s3_bucket.test1.arn}/*"
},
]
})  
}
```
Before this PR, our `tf` loader would render `policy` out to `null` because our method of evaluating most functions does not currently handle resource attributes. This PR adds a special case for `jsonencode` because this usage is so prevalent in the Terraform documentation. We'll follow up with a more complete solution to evaluate functions with resources / …
=> [RM-5839] Support template strings in jsonencode

Makefile
* Adds documentation (the help target)
* Switches to variables which can be overridden (?= instead of =) for
some things.
* Uses new variables to make more things configurable (docker, go)
* Use install instead of cp for installing binary
* Make building the binary the default for a plain `make`
=> Add make help target, assorted other Makefile improvements

pkg/reporter/base.go
Sample output:
```json
{
"controls": [
"CIS-AWS_v1.2.0_4.3",
"CIS-AWS_v1.3.0_5.3"
],
"filepath": "rego/tests/examples/aws/inputs/tag_all_resources_infra.json",
"input_type": "tf_plan",
"provider": "aws",
"resource_id": "aws_vpc.untagged",
"resource_type": "aws_vpc",
"rule_description": "VPC default security group should restrict all traffic. Configuring all VPC default security groups to restrict all traffic encourages least privilege security group development and mindful placement of AWS resources into security groups which in turn reduces the exposure of those resources.",
"rule_id": "FG_R00089",
"rule_message": "",
"rule_name": "tf_aws_vpc_default_security_group",
"rule_result": "FAIL",
"rule_severity": "Medium",
"rule_summary": "VPC default security group should restrict all …
```
=> Add remediation documentation URLs to JSON output.

pkg/regotools/metadoc/metadoc.go, pkg/regotools/metadoc/metadoc_test.go
Basically, instead of something like:
```
__rego__metadoc__ := {
"id": "FG_R00011",
"title": "CloudFront viewer protocol policy should be set to https-only or redirect-to-https",
"description": "CloudFront viewer protocol policy should be set to https-only or redirect-to-https. CloudFront connections should be encrypted during transmission over networks that can be accessed by malicious individuals. A CloudFront distribution should only use HTTPS or Redirect HTTP to HTTPS for communication between viewers and CloudFront.",
"custom": {
"severity": "Medium",
"families": [
"More rules",
"e6f9b788-1841-4466-8db7-28d2f08da2ff"
]
}
}
```
With this patch we now prefer something like:
```
__rego__metadoc__ := {
"id": "FG_R00011",
"title": "CloudFront viewer protocol policy should be set to …
```
=> [RM-5867] Use __rego__metadoc__ for provider instead of header

pkg/reporter/base.go
This was causing the JSON to write a field called "rule_remediaion_doc" instead of "rule_remediation_doc".  Thanks to @becki-at-luminal for spotting it.
=> Fix typo in "remediation" (the "t" was missing)

docs/src/examples/waive-and-disable.md, docs/src/getting-started.md, docs/src/report.md, docs/src/usage.md
This PR updates the docs site:
- Refactor the Report page to include updated output (gathered from running Regula on the regula-ci-example repo) and a list of report attributes
- Document the new `compact` output format
- Update sample output with the new `rule_remediation_doc` field
=> Docs updates for 1.4.0 release

go.mod, go.sum, pkg/regotools/metadoc/metadoc.go, pkg/regotools/metadoc/metadoc_test.go
[HuJSON](https://github.com/tailscale/hujson) is a fork of encoding/json which allows embedded comments and trailing commas.  The API is compatible so all that is necessary is to import HuJSON instead of encoding/json; as long as the imported name remains the same no further code changes are necessary.
=> Parse metadoc using HuJSON instead of encoding/json.

Dockerfile
This PR is in response to #215. Switching the regula docker image from scratch to Alpine has a negligible impact on size (21.5MB -> 28.5MB) and enables the regula docker image to run in more places.
=> [RM-6152] Switch docker image to use alpine instead of scratch

Makefile
`brew install` or `brew upgrade` for `regula` currently shows the following:
```sh
Warning: Calling bottle :unneeded is deprecated! There is no replacement.
Please report this issue to the fugue/regula tap (not Homebrew/brew or Homebrew/core):
/usr/local/Homebrew/Library/Taps/fugue/homebrew-regula/Formula/regula.rb:9
```
The generation is fixed in https://github.com/goreleaser/goreleaser/pull/2591 and available with GoReleaser v0.183.0.
Signed-off-by: Timofey Ilinykh <ilinytim@gmail.com>
=> Remove deprecated bottle `:unneeded` from homebrew formula

pkg/regulatf/moduletree.go, pkg/regulatf/regulatf.go
Two small changes:
-  Support the `count.index` attribute, since it's often used together
with `count = 0 / 1`.
-  Make the output less verbose in case there are many errors, these
are not really helpful to users anyway, assuming the TF is valid.
=> Support count.index attribute, less verbose

cmd/flags.go, cmd/init.go, cmd/repl.go, cmd/run.go, cmd/runconfig.go, cmd/showconfigrego.go, cmd/showinput.go, cmd/showscanview.go, cmd/write_test_inputs.go
This PR replaces the use of the global viper instance with a command-specific one. This was causing a last-write-wins bug where commands were overwriting each other's flags in the global viper instance.
=> [RM-6215] Use command-specific viper instead of global

rego/lib/aws/security_groups/library.rego, rego/rules/tf/aws/elb/access_log_enabled.rego
This PR adds support for the aws_alb resource type to our rules. aws_alb is an alias for aws_lb and is identical in every way except the name.
=> [RM-6258] Support aws_alb resource type

rego/lib/aws/s3/s3_library.rego
This PR fixes an issue where bucket policies that are related to buckets by bucket name (rather than by reference) were not getting picked up by `bucket_policies_for_bucket`.
=> [RM-6309] Match bucket or ID in bucket_policies_for_bucket

rego/lib/aws/lambda/permissions_library.rego
This PR resolves an issue where lambda permissions that are related to functions by reference were not getting picked up by our lambda permissions library #200
=> [RM-6200] Allow for function ID in permission.function_name field

rego/rules/tf/aws/cloudfront/http_monitor.rego
This PR converts `FG_R00073` to a simple rule. The AWS API validates `web_acl_id` on creation:
```
Error: error creating CloudFront Distribution: InvalidWebACLId: Invalid webACL identifier provided foobar
status code: 400, request id: 00000000-0000-0000-0000-000000000000
```
So, it's unnecessary and out-of-scope for Regula to validate this field. Since we also do not need to inspect any properties on the WAF for this rule, it's enough for us to check that this field is set.
=> [RM-6259] Convert FG_R00073 to simple rule

Makefile
This also adds remediation as a dependency for the bump targets so it
is automatically run when creating a new release.  I also removed the
rego/remediation.yaml target, which wasn't really useful since the
file is included in git not regenerated every time.
I have intentionally not updated rego/remediation.yaml to make testing
easier.
=> Makefile: unconditionally regenerate links for remediation target

pkg/loader/tf_test/ternary-mismatch.json, pkg/loader/tf_test/ternary-mismatch/main.tf, pkg/regulatf/moduletree.go, pkg/regulatf/regulatf.go, pkg/regulatf/valtree.go, pkg/regulatf/valtree_test.go
This PR replaces our use of `cty.NilVal` with `cty.NullVal`. The included `ternary-mismatch.json` resulted in a panic from this line:
```
bucket = var.foo ? {"foo": "bar"} : aws_s3_bucket.foo.bucket
```
because the HCL library's error handling for mismatched conditional return types attempts to call a `FriendlyName()` method on each return type. `cty.NilVal.Type()` returns a native `nil` value, which results in a panic.
=> [RM-6416] Replace cty.NilVal with cty.NullVal

rego/rules/tf/aws/waf/known_bad_inputs.rego, rego/rules/tf/azurerm/sql/auditing_retention_90days.rego
Adds a new rule to detect the presence of the `AWSManagedRulesKnownBadInputsRuleSet` AWS rule set for AWS WAF.
Also see https://github.com/LuminalHQ/risk-manager/pull/4014
=> Add waf known bad inputs rule

docs/src/rules.md
This PR adds FG_R00500 to the table on the Rules page of the docs site and also separates the rules by provider and input type. Previously, AWS CloudFormation and AWS Terraform rules were combined into the same table.
=> Docs: Update rules table

cmd/runconfig.go
Attempting to upload a scan without an environment ID results in an HTTP 400 (Bad Request) status. This change requires a value for this field either from the command line or the config file.
=> [RM-6462] Require an environment ID for uploads

docs/README.md, docs/scripts/rules_tables.py, docs/src/rules.md
This PR updates the script that generates the rules list for the docs site.
- Generate table for a single provider by running script with `--provider` argument (`aws`, `azurerm`, `google`, `cfn`, `arm`, `k8s`), or generate for all using `--provider all` (default)
- Example: `python docs/scripts/rules_tables.py --provider k8s`
- Determine resource type for each rule
- Print table at H2 level
Instructions for running the script have been added to the docs README.
=> Docs: Update rule table script

rego/lib/fugue/resource_view/terraform.rego, rego/tests/lib/fugue_resource_view_issue256_test.rego
This PR tightens up the rules around how we detect modules when using
the terraform plan input, fixing an issue where we would detect two different
blobs of JSON as a module, which leads to the issue described in #256.
=> [RM-6363] Fix issue around module detection

docs/src/fugue.md, docs/src/report.md, mkdocs.yml
This adds a page that explains how to use Regula with Fugue.
Also documents `families` in the JSON report output.
=> Docs: Add Regula and Fugue page

rego/lib/fugue/resource_view/arm.rego, rego/tests/lib/fugue_resource_view_arm_test.rego
This PR makes the `provider` value for ARM inputs match what we would get from Terraform. This is consistent with how we handle Cloudformation inputs.
=> Change arm provider to "azurerm"

pkg/reporter/table.go
Signed-off-by: Fabiano Graças <fabiano.gracas@faro.com>
Hi guys, we have started to use regula as part of our pipelines, although regula table format delivers nice content It delivers also a wide-sized table, in our pipeline, the disposition of the columns would be nicer with this change. which would look like more to a unit test table results.
The change consists in bringing the result and severity to the very beginning of the table in order to see them first.
before:
after:
my best regards,
Fabiano
=> change table reporter column disposition

pkg/loader/tf_test/tags.json, pkg/loader/tf_test/tags/main.tf, pkg/loader/tf_test/vars.json, pkg/regulatf/regulatf.go, pkg/regulatf/tags.go, pkg/reporter/base.go, rego/lib/fugue/resource_view/tags.rego, rego/lib/fugue/resource_view/terraform.rego, rego/tests/lib/fugue_resource_view_07_test.rego, rego/tests/lib/inputs/resource_view_07_infra.json, rego/tests/lib/inputs/resource_view_07_infra.tf, rego/tests/lib/inputs/resource_view_07_infra_json.rego
These are necessary for the google terraform provider, in order to be consistent
with Fugue.
=> Add support for valueless tags

pkg/loader/tf_test/count-ref.json, pkg/loader/tf_test/count-ref/main.tf, pkg/regulatf/expr.go, pkg/regulatf/moduletree.go, pkg/regulatf/names.go, pkg/regulatf/names_test.go, pkg/regulatf/regulatf.go, pkg/regulatf/value.go
This significantly improves support for the way we handle `count` in HCL. ere
Thare several parts to this PR which work together:
1.  For resources that have a `count`, we structure them as a singleton array
in the `ValTree`.  This way, it matches up with what the vanilla HCL
evaluator expects.  So for:
resource "aws_s3_bucket" "mybucket" {
count = 3  # Actual number does not matter if it's not 0
bucket_prefix = "foo"
}
We get:
"aws_s3_bucket": {
"mybucket": [
{
"count": 3,
"bucket_prefix": "foo"
}
]
}
This way, references like `aws_s3_bucket.mybucket[0].bucket_prefix` work as
expected.
2.  More often than not, we do not refer to these properties as:
aws_s3_bucket.mybucket[0].bucket_prefix
Something like this is much more common:
aws_s3_bucket.mybucket[count.index].bucket_prefix
However, …
=> Improve support for `count` attribute in HCL

docs/src/configuration.md, docs/src/development/writing-rules.md, docs/src/examples/debug-tutorial.md, docs/src/examples/waive-and-disable.md, docs/src/examples/writing-a-rule.md, docs/src/fugue.md, docs/src/getting-started.md, docs/src/report.md, docs/src/usage.md
This PR updates the docs for the following:
- New SARIF output format
- Updated table output format
- New `active_waivers` and `resource_tags` fields in JSON output
- Syncing waivers from Fugue to Regula
- Updated output for examples throughout
=> Docs updates for v2.6.0

.github/workflows/main.yml, .github/workflows/release.yml, README.md, docs/src/getting-started.md, go.mod
- ci: build/test with go{1.17, 1.18}, release with go1.18
- deps: update go requirement to 1.17+ (as go1.16 is not maintained)
---
action run ref, https://github.com/chenrui333/regula/actions/runs/2009828046
=> deps: update to use go1.18

mkdocs.yml
This PR fixes the "Edit this page" links on each page of the docs site. These links broke when we moved the docs to `docs/src/`.
=> Docs: Fix 'Edit on GitHub' link

rego/lib/aws/s3/s3_library.rego, rego/lib/aws/security_groups/library.rego, rego/rules/tf/aws/cloudtrail/s3_access_logging.rego, rego/rules/tf/aws/cloudtrail/target.rego, rego/rules/tf/aws/kms/key_not_public.rego, rego/rules/tf/aws/kms/key_rotation.rego, rego/rules/tf/aws/s3/bucket_access_logging.rego, rego/rules/tf/aws/s3/bucket_config_public_read.rego, rego/rules/tf/aws/s3/bucket_is_public.rego, rego/rules/tf/aws/s3/replication.rego, rego/rules/tf/aws/s3/versioning_lifecycle_enabled.rego, rego/rules/tf/aws/security_groups/inbound_all.rego, rego/tests/rules/tf/aws/kms/key_rotation_test.rego
This PR updates the following rules to support the constructs added in the Terraform AWS Provider v4:
* FG_R00028: S3 bucket ACLs should not have public access on S3 buckets that store CloudTrail log files
* FG_R00031: S3 bucket access logging should be enabled on S3 buckets that store CloudTrail log files
* FG_R00036: KMS CMK rotation should be enabled
* FG_R00044: VPC security group inbound rules should not permit ingress from a public address to all ports and protocols
* FG_R00101: S3 bucket versioning and lifecycle policies should be enabled
* FG_R00252: KMS master keys should not be publicly accessible
* FG_R00274: S3 bucket access logging should be enabled
* FG_R00275: S3 bucket replication (cross-region or same-region) should be enabled
* FG_R00277: S3 buckets should not be …
=> [CLOUD-242] Update TF AWS rules for provider v4

changes/unreleased/Added-20220614-094302.yaml, cmd/flags.go, cmd/init.go, cmd/run.go, cmd/runconfig.go, cmd/showinput.go, docs/src/configuration.md, docs/src/usage.md, pkg/loader/base.go, pkg/loader/loadpaths.go, pkg/loader/tf.go, pkg/loader/tf_test/tfvars-01.json, pkg/loader/tf_test/tfvars-01/aaa.auto.tfvars, pkg/loader/tf_test/tfvars-01/bbb.auto.tfvars.json, pkg/loader/tf_test/tfvars-01/ccc.auto.tfvars, pkg/loader/tf_test/tfvars-01/main.tf, pkg/loader/tf_test/tfvars-01/terraform.tfvars, pkg/loader/tf_test/tfvars-01/terraform.tfvars.json, pkg/loader/tf_test/tfvars-02.json, pkg/loader/tf_test/tfvars-02/main.tf, pkg/loader/tf_test/tfvars-02/terraform.tfvars, pkg/regulatf/moduletree.go, pkg/regulatf/names.go, pkg/regulatf/regulatf.go, pkg/regulatf/varfiles.go
This PR adds support for tfvars files. After this change, Regula will automatically load `terraform.tfvars`, `*.auto.tfvars`, and their JSON equivalents. Users will also have the option to manually specify tfvars files (and their JSON equivalents) with the `--var-file` option, which can be specified more than once.
=> [CLOUD-266] tfvars support

pkg/regotools/metadoc/metadoc.go, pkg/regotools/metadoc/metadoc_test.go
This PR is related to https://github.com/fugue/regula/pull/247.
As part of metadoc, we can specify custom remediation doc link for custom rule. This PR makes it so that regotools support that as well when processing metadoc.
=> Added support for remediation doc to regotools metadoc
