- rules/REGULA_R00004.rego
- rules/REGULA_R00009.rego
- tests/rules/REGULA_R00004_test.rego
- tests/rules/REGULA_R00009_test.rego
- tests/rules/inputs/REGULA_R00004_infra.rego
- tests/rules/inputs/REGULA_R00004_infra.tf
- tests/rules/inputs/REGULA_R00009_infra.rego
- tests/rules/inputs/REGULA_R00009_infra.tf
What:
Rules and test files for REGULA_R00004 and REGULA_R00009.
Unit Tests:
Used Fregot.
> REGULA_R00004 and REGULA_R00009

- rules/cloudtrail_log_file_validation_enabled.rego
- tests/rules/cloudtrail_log_file_validation_enabled_test.rego
- tests/rules/inputs/cloudtrail_log_file_validation_enabled.rego
- tests/rules/inputs/cloudtrail_log_file_validation_enabled.tf
Adds CloudTrail log file validation should be enabled rule and associated CIS control mapping.
Added and ran unit test
Ran full report with fregot
> [REGULA_R00006] CloudTrail log file validation should be enabled

- README.md
> Edit README to add blog post link

- README.md
- bin/regula
Updates regula to work with subdirectories. See this [Terraform issue](https://github.com/hashicorp/terraform/issues/21966) for more details.
> Project subdirectory support

- .github/workflows/main.yml
- lib/fugue_regula.rego
> Workaround for comprehension bug in OPA >= 0.20.x

- bin/regula
- lib/fugue/regula.rego
- tests/lib/fugue_regula_report_01_test.rego
- tests/lib/fugue_regula_report_02_test.rego
> [RM-5292] Support multiple input paths

- README.md
> 0.7 readme

- README.md
This PR:
- Corrects one of the waiver examples
- Clarifies some of the attributes for specifying waivers and disabling rules
- Provides examples of multiple waivers, multiple disabled rules
- Updates sample report output
> Update README to clarify waivers and disabling rules

- pkg/reporter/table.go
> Table output overall result should be left-aligned

- rego/rules/tf/azurerm/storage/account_microsoft_services.rego
This PR updates the description in the metadata for `tf_azurerm_storage_account_microsoft_services` (FG_R00208).
> [RM-5749] Update FG_R00208 description

- README.md
- docs/src/development/writing-rules.md
- docs/src/examples/waive-and-disable.md
- docs/src/examples/writing-a-rule.md
- docs/src/getting-started.md
- docs/src/report.md
- docs/src/usage.md
This PR updates the docs for the 1.1.0 release:
- New output shows path, line, and column of a resource
- PowerShell installation has been added to README
> Docs updates for 1.1.0

- docs/src/getting-started.md
- pkg/reporter/text.go
- pkg/reporter/text.tmpl
Adds whitespace and formats the docs URL
> Adjust text output format

- Makefile
- pkg/reporter/base.go
- pkg/reporter/compact.go
- pkg/reporter/compact.tmpl
- pkg/reporter/text.go
I haven't tested *extensively*, but here is a first stab at a compact output mode:
> Add compact output mode.

- rego/rules/tf/aws/ec2/asg.rego
This PR adds a new condition to rule `FG_R00014` that checks the availability zones on subnets attached to the autoscaling group.
> [RM-6027] Enhance ASG AZ rule by inspecting vpc_zone_identifier

- docs/src/usage.md
Documentation added to the Usage page.
> Document REGULA_FORMAT environment variable

- docs/src/rules.md
For the rules page on the docs site: This PR adds a new rule (FG_R00499) and updates the severity for FG_R00377.
> Docs: Update rules page

- go.mod
- go.sum
See <https://github.com/advisories/GHSA-f6mq-5m25-4r72>
> Bump mongo-driver dependency

- docs/src/configuration.md
- docs/src/development/writing-rules.md
- docs/src/examples/debug-tutorial.md
- docs/src/examples/waive-and-disable.md
- docs/src/examples/writing-a-rule.md
- docs/src/getting-started.md
- docs/src/report.md
- docs/src/usage.md
This PR updates the Regula docs with content for the v2.0.0 release.
> Docs updates for v2.0.0

- pkg/loader/tf_test/issue-245.json
- pkg/loader/tf_test/issue-245/test.tf
- pkg/regulatf/moduletree.go
> Don't visit variables without a default

- rego/lib/fugue/resource_view/arm.rego
- rego/rules/arm/mysql/no_inbound_all.rego
- rego/rules/arm/postgresql/no_inbound_all.rego
- rego/rules/arm/sql/no_inbound_all.rego
- rego/tests/lib/fugue_resource_view_arm_test.rego
- rego/tests/lib/inputs/arm_resource_view_01.rego
- rego/tests/rules/arm/mysql/inputs/no_inbound_all_infra.json
- rego/tests/rules/arm/mysql/inputs/no_inbound_all_infra_json.rego
- rego/tests/rules/arm/mysql/no_inbound_all_test.rego
- rego/tests/rules/arm/postgresql/inputs/no_inbound_all_infra.json
- rego/tests/rules/arm/postgresql/inputs/no_inbound_all_infra_json.rego
- rego/tests/rules/arm/postgresql/no_inbound_all_test.rego
- rego/tests/rules/arm/sql/inputs/no_inbound_all_infra.json
- rego/tests/rules/arm/sql/inputs/no_inbound_all_infra_json.rego
- rego/tests/rules/arm/sql/no_inbound_all_test.rego
This adds a refinement of the resource view, and three rules:
- FG_R00221 SQL Server firewall rules should not permit start and end IP addresses to be 0.0.0.0
- FG_R00222 MySQL Database server firewall rules should not permit start and end IP addresses to be 0.0.0.0
- FG_R00223 PostgreSQL Database server firewall rules should not permit start and end IP addresses to be 0.0.0.0
> [RM-6366] ARM resource view update & rules for database firewalls

- docs/src/integrations/bitbucket-pipelines.md
- mkdocs.yml
This PR adds a new page, Regula + Bitbucket Pipelines.
> Docs: Add link to Bitbucket Pipelines integration

- pkg/rego/runrepl.go
- pkg/rego/runrules.go
- pkg/rego/runtest.go
- pkg/rego/runtime.go
> [RM-6633] Provide info for opa.runtime()

- pkg/loader/tf_test/issue-305.json
- pkg/loader/tf_test/issue-305/main.tf
- pkg/regulatf/regulatf.go
> Set terraform.workspace to "default"

- pkg/loader/tf_test/null-count.json
- pkg/loader/tf_test/null-count/main.tf
- pkg/regulatf/value.go
This PR fixes a panic arising from null expressions in `count`.
> [RM-6663] Fix panic from null count

- rego/rules/tf/aws/cloudwatch/encrypted_logs.rego
> Refactor and update FG_R00068 to a simple rule

- rego/lib/aws/iam/policy_document_library.rego
- rego/lib/aws/security_groups/library.rego
- rego/lib/aws/vpc/nacl_library.rego
- rego/lib/azurerm/postgresql/configuration.rego
- rego/lib/fugue.rego
- rego/lib/google/compute/compute_instance_library.rego
- rego/lib/google/iam/policy_library.rego
- rego/lib/google/kms/kms_policy_library.rego
- rego/lib/google/storage/bucket_policy_library.rego
- rego/rules/arm/monitor/log_profile_global_locations.rego
- rego/rules/tf/aws/elb/access_log_enabled.rego
- rego/rules/tf/aws/rds/multi_az_cluster.rego
- rego/rules/tf/aws/vpc/default_security_group.rego
- rego/rules/tf/azurerm/monitor/log_profile_locations.rego
This will eventually replace resource_types_v0
> [RM-6616] Add input_resource_types

- .goreleaser.yml
- changes/unreleased/Fixed-20220322-120055.yaml
This PR fixes the `regula version` output for the official release artifacts.
> Fix regula version output

- rego/rules/tf/aws/kms/key_not_public.rego
> FG_R00252 should support arrays for condition values

- rego/rules/tf/aws/kms/key_not_public.rego
See issue https://github.com/fugue/regula/issues/386
> Proposed fix for issue 386

- .snyk
- add `.snyk` file to ignore MPL2 licence issues
> chore: ignore licence issues
